//! End-to-end tests on test_fixtures/ (generated by scripts/make-fixtures.py):
//! crawl → extract → index → search → preview.

use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;
use std::sync::OnceLock;

use prospector_core::{Engine, SearchRequest, SiteRecord};

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("test_fixtures").canonicalize().unwrap()
}

/// Temporary folders go in target/ (next to the project), not in the system TEMP.
fn temp_dir() -> tempfile::TempDir {
    tempfile::tempdir_in(env!("CARGO_TARGET_TMPDIR")).unwrap()
}

/// One engine indexed once for all the tests of this file.
fn engine() -> &'static (Engine, SiteRecord, tempfile::TempDir) {
    static ENGINE: OnceLock<(Engine, SiteRecord, tempfile::TempDir)> = OnceLock::new();
    ENGINE.get_or_init(|| {
        let data = temp_dir();
        let engine = Engine::open(data.path()).unwrap();
        let site = engine.add_site("Fixtures", vec![fixtures().to_string_lossy().into_owned()]).unwrap();
        let site = engine.index_site(&site.id, &[], &AtomicBool::new(false), &|_| {}).unwrap();
        (engine, site, data)
    })
}

fn search(query: &str, fuzzy: bool) -> Vec<String> {
    search_with(SearchRequest { query: query.into(), fuzzy, ..Default::default() })
}

fn search_with(req: SearchRequest) -> Vec<String> {
    let (engine, site, _) = engine();
    let response = engine.search(std::slice::from_ref(&site.id), &req).unwrap();
    let mut names: Vec<String> = response
        .hits
        .iter()
        .map(|h| Path::new(&h.path).file_name().unwrap().to_string_lossy().into_owned())
        .collect();
    names.sort();
    names
}

#[test]
fn indexes_every_supported_file_and_counts_the_others() {
    let (_, site, _) = engine();
    // Étape 1: 8 text/code/mail + 3 docx + 2 pdf = 13. Étape 2 adds xlsx, pptx,
    // 3 zip entries and 2 msg = 20. Étape 3 adds 2 rar + 2 7z entries = 24.
    // Lot 5.2 (OCR, Windows) adds 3 images and a scanned PDF = 28.
    // Lot 5.3 adds 16: legacy/ (3 .doc, 2 .ppt, rtf, odt, odp, README), an EPUB,
    // .gz, .bz2, 2 tar.gz entries, a .jar entry and a protected PDF.
    // Lot 5.4 adds 12: attachments of the existing .msg files (4), a .msg with
    // its attached .doc (2), an .eml with 2 attachments (3), an mbox (3).
    // node_modules is excluded.
    let ocr = if prospector_core::extract::ocr::enabled() { 4 } else { 0 };
    assert_eq!(site.doc_count, 54 + ocr, "indexed documents");
    assert_eq!(site.skipped.get("binary"), Some(&1));
    assert_eq!(site.skipped.get("corrupt"), Some(&2));
    assert!(site.last_indexed.is_some());
}

#[test]
fn finds_words_in_every_format_but_never_in_node_modules() {
    let names = search("contrat", false);
    for expected in ["contrat-prestation.docx", "contrat-prestation.pdf", "notes-contrat.txt", "signature.eml", "windows-1252.txt"] {
        assert!(names.contains(&expected.to_owned()), "{expected} missing from {names:?}");
    }
    assert!(!names.contains(&"contract.js".to_owned()));
}

#[test]
fn accents_and_encodings_do_not_matter() {
    assert_eq!(search("resume", false), ["windows-1252.txt"]);
    assert_eq!(search("cancion", false), ["utf16-bom.txt"]);
}

#[test]
fn arabic_with_or_without_vowels_and_article() {
    let names = search("عقد", false);
    assert!(names.contains(&"ملاحظات.txt".to_owned()), "{names:?}");
    assert!(names.contains(&"عقد_إيجار.docx".to_owned()), "{names:?}");
}

#[test]
fn stems_find_plurals() {
    let names = search("contratos", false);
    assert!(names.contains(&"contrato_servicios.docx".to_owned()), "{names:?}");
    assert!(names.contains(&"notas.md".to_owned()), "{names:?}");
}

#[test]
fn fuzzy_finds_typos_only_when_enabled() {
    assert!(!search("contrat", false).contains(&"ContractService.ts".to_owned()));
    assert!(search("contrat", true).contains(&"ContractService.ts".to_owned()));
}

#[test]
fn phrases_and_booleans() {
    let phrase = search("\"contrat de prestation\"", false);
    assert!(phrase.iter().all(|n| n.starts_with("contrat-prestation") || n == "notes-contrat.txt"), "{phrase:?}");
    assert!(!phrase.is_empty());

    let or = search("agreement OR contrato", false);
    assert!(or.contains(&"readme.md".to_owned()) && or.contains(&"notas.md".to_owned()), "{or:?}");

    let not = search("contrat NOT résiliation", false);
    assert!(not.contains(&"signature.eml".to_owned()), "{not:?}");
    assert!(!not.contains(&"notes-contrat.txt".to_owned()), "{not:?}");
}

#[test]
fn filters_by_kind_and_language() {
    let pdf = search_with(SearchRequest { query: "contrat".into(), kinds: vec!["pdf".into()], ..Default::default() });
    assert_eq!(pdf, ["contrat-prestation.pdf"]);
    // Every hit must be a Spanish document (utf16-bom.txt is Spanish too).
    let (engine, site, _) = engine();
    let req = SearchRequest { query: "contrato".into(), langs: vec!["es".into()], ..Default::default() };
    let hits = engine.search(std::slice::from_ref(&site.id), &req).unwrap().hits;
    assert!(hits.len() >= 3, "{hits:?}");
    assert!(hits.iter().all(|h| h.lang == "es"), "{hits:?}");
}

#[test]
fn hits_carry_marked_snippets_and_counts() {
    let (engine, site, _) = engine();
    let response = engine.search(std::slice::from_ref(&site.id), &SearchRequest { query: "contrat".into(), ..Default::default() }).unwrap();
    let hit = response.hits.iter().find(|h| h.path.ends_with("notes-contrat.txt")).unwrap();
    assert!(hit.match_count >= 3, "match count {}", hit.match_count);
    assert!(hit.snippets[0].text.contains("⟦contrat⟧"), "{:?}", hit.snippets);
    assert_eq!(hit.snippets[0].line, 1);
    assert_eq!(hit.lang, "fr");
}

#[test]
fn preview_marks_every_occurrence() {
    let (engine, site, _) = engine();
    let path = fixtures().join("fr").join("contrat-prestation.docx");
    let req = SearchRequest { query: "contrat".into(), ..Default::default() };
    let preview = engine.preview(&site.id, &path.to_string_lossy(), &req).unwrap();
    assert_eq!(preview.layout, "prose");
    assert_eq!(preview.lines.len(), 3);
    assert!(preview.match_count >= 3);
    assert!(preview.lines[0].text.contains("⟦contrat⟧"));
}

#[test]
fn missing_root_is_reported_as_a_code() {
    let data = temp_dir();
    let engine = Engine::open(data.path()).unwrap();
    let site = engine.add_site("Gone", vec!["Z:\\does\\not\\exist".into()]).unwrap();
    let err = engine.index_site(&site.id, &[], &AtomicBool::new(false), &|_| {}).unwrap_err();
    let json = serde_json::to_value(&err).unwrap();
    assert_eq!(json["code"], "rootUnavailable");
    assert_eq!(json["params"]["path"], "Z:\\does\\not\\exist");
}
